name: update manifests

on:
  push:
    branches: ['main']

jobs:  
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: yq-update-manifests
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq eval '.images.0.newTag = "${{ github.sha }}"' -i deployments/kustomize/kustomization.yaml

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply image tag change